In [1]:
import numpy as np

In [2]:
A = np.identity(10)
A[np.arange(9), np.arange(9)+1] = 1
A

array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [3]:
A_eval, A_evec = np.linalg.eig(A)
print(A_eval)
print(A_evec)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[ 1.00000000e+000 -1.00000000e+000  1.00000000e+000 -1.00000000e+000
   1.00000000e+000 -1.00000000e+000  1.00000000e+000 -1.00000000e+000
   1.00000000e+000 -1.00000000e+000]
 [ 0.00000000e+000  2.22044605e-016 -2.22044605e-016  2.22044605e-016
  -2.22044605e-016  2.22044605e-016 -2.22044605e-016  2.22044605e-016
  -2.22044605e-016  2.22044605e-016]
 [ 0.00000000e+000  0.00000000e+000  4.93038066e-032 -4.93038066e-032
   4.93038066e-032 -4.93038066e-032  4.93038066e-032 -4.93038066e-032
   4.93038066e-032 -4.93038066e-032]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  1.09476443e-047
  -1.09476443e-047  1.09476443e-047 -1.09476443e-047  1.09476443e-047
  -1.09476443e-047  1.09476443e-047]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   2.43086534e-063 -2.43086534e-063  2.43086534e-063 -2.43086534e-063
   2.43086534e-063 -2.43086534e-063]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000

In [4]:
A_tilde = A.copy()
A_tilde[9, 0] = 10**-10
A_tilde

array([[1.e+00, 1.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 1.e+00, 1.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 1.e+00, 1.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00, 1.e+00, 1.e+00, 0.e+00, 0.e+00, 0.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00, 0.e+00, 1.e+00, 1.e+00, 0.e+00, 0.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 1.e+00, 1.e+00, 0.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 1.e+00, 1.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 1.e+00,
        1.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
        1.e+00, 1.e+00],
       [1.e-10, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
        0.e+00, 1.e+00]])

In [5]:
A_tilde_eval, A_tilde_evec = np.linalg.eig(A_tilde)
print(A_tilde_eval)
print(A_tilde_evec)

[0.9      +0.j         0.9190983+0.05877853j 0.9190983-0.05877853j
 0.9690983+0.09510565j 0.9690983-0.09510565j 1.0309017+0.09510565j
 1.0309017-0.09510565j 1.0809017+0.05877852j 1.0809017-0.05877852j
 1.1      +0.j        ]
[[ 9.94987437e-01+0.00000000e+00j  9.94987437e-01+0.00000000e+00j
   9.94987437e-01-0.00000000e+00j  9.94987437e-01+0.00000000e+00j
   9.94987437e-01-0.00000000e+00j  9.94987437e-01+0.00000000e+00j
   9.94987437e-01-0.00000000e+00j  9.94987437e-01+0.00000000e+00j
   9.94987437e-01-0.00000000e+00j  9.94987437e-01+0.00000000e+00j]
 [-9.94987478e-02+0.00000000e+00j -8.04961757e-02+5.84838981e-02j
  -8.04961757e-02-5.84838981e-02j -3.07467993e-02+9.46289308e-02j
  -3.07467993e-02-9.46289308e-02j  3.07468058e-02+9.46289260e-02j
   3.07468058e-02-9.46289260e-02j  8.04961732e-02+5.84838907e-02j
   8.04961732e-02-5.84838907e-02j  9.94987401e-02+0.00000000e+00j]
 [ 9.94987520e-03+0.00000000e+00j  3.07468000e-03-9.46289364e-03j
   3.07468000e-03+9.46289364e-03j -8.04961810e-

In [6]:
diff = np.abs(A_tilde_eval.real - A_eval)

In [7]:
diff.mean()

0.06472135948651472

In [68]:
p = lambda z: z ** 6 - 1
g = lambda z: (6 * z ** 5) / (z**6 - 1)
# u_prime = lambda z: -(6 * z ** 4 * (z**6 + 5))/((z**6 - 1)**2)
h = lambda z: g(z) ** 2 - (30 * z ** 4) / (z**6 -1)



In [72]:
def laguerre(x, g, h, n=6):
    L_p = (g(x) + np.sqrt((n - 1) * (n * h(x) - g(x) ** 2)))
    L_m = (g(x) - np.sqrt((n - 1) * (n * h(x) - g(x) ** 2)))

    if abs(L_p) > abs(L_m):
        return x - n / L_p
    else:
        return x - n / L_m
    
def L(x):
    s = np.sign((x ** 3).real)
    z = s * x ** 3
    return x ** -2 * s * (1 + 5*z)/(z + 5)

In [83]:
rand_p = np.apply_along_axis(lambda args: [complex(*args)], 0, np.random.rand(2,100))[0]
print(rand_p)

[0.53013141+0.51673419j 0.14189965+0.46029911j 0.6740753 +0.07785573j
 0.02517727+0.12611239j 0.10131498+0.5148476j  0.24918406+0.41853627j
 0.87188091+0.5277443j  0.05461991+0.47235878j 0.86515038+0.71532905j
 0.38405423+0.45272648j 0.09827786+0.32860811j 0.43890008+0.07937482j
 0.34473309+0.23977657j 0.41574503+0.07102615j 0.37085045+0.30000084j
 0.53033576+0.76635452j 0.62042105+0.07847151j 0.0637122 +0.75262976j
 0.67109443+0.72258173j 0.88806735+0.89234018j 0.87611121+0.61852795j
 0.48017803+0.06843598j 0.8552064 +0.86632597j 0.13461025+0.46835912j
 0.06598976+0.11381803j 0.82660892+0.3827198j  0.99069508+0.06317163j
 0.7230543 +0.42516171j 0.27534877+0.19127397j 0.96690434+0.6573417j
 0.1419764 +0.32963666j 0.9985082 +0.69422355j 0.93657562+0.13422055j
 0.10920798+0.83446859j 0.43699015+0.50174146j 0.72155745+0.76287791j
 0.50773776+0.85488213j 0.22197299+0.66954417j 0.20267703+0.03960482j
 0.00810559+0.53438676j 0.17552919+0.91125012j 0.00177393+0.94862155j
 0.44174514+0.6460979

In [84]:
lag = []
an = []
for c in rand_p:
    lag.append(laguerre(c, g, h))
    an.append(L(c))
lag = np.array(lag)
an = np.array(an)

In [86]:
(abs((lag - an))**2).mean()

3.535411739111698e-31