In [2]:
import numpy as np

In [3]:
A = np.identity(10)
A[np.arange(9), np.arange(9)+1] = 1
A

array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [4]:
A_eval, A_evec = np.linalg.eig(A)
print(A_eval)
print(A_evec)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[ 1.00000000e+000 -1.00000000e+000  1.00000000e+000 -1.00000000e+000
   1.00000000e+000 -1.00000000e+000  1.00000000e+000 -1.00000000e+000
   1.00000000e+000 -1.00000000e+000]
 [ 0.00000000e+000  2.22044605e-016 -2.22044605e-016  2.22044605e-016
  -2.22044605e-016  2.22044605e-016 -2.22044605e-016  2.22044605e-016
  -2.22044605e-016  2.22044605e-016]
 [ 0.00000000e+000  0.00000000e+000  4.93038066e-032 -4.93038066e-032
   4.93038066e-032 -4.93038066e-032  4.93038066e-032 -4.93038066e-032
   4.93038066e-032 -4.93038066e-032]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  1.09476443e-047
  -1.09476443e-047  1.09476443e-047 -1.09476443e-047  1.09476443e-047
  -1.09476443e-047  1.09476443e-047]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   2.43086534e-063 -2.43086534e-063  2.43086534e-063 -2.43086534e-063
   2.43086534e-063 -2.43086534e-063]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000

In [5]:
A_tilde = A.copy()
A_tilde[9, 0] = 10**-10
A_tilde

array([[1.e+00, 1.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 1.e+00, 1.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 1.e+00, 1.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00, 1.e+00, 1.e+00, 0.e+00, 0.e+00, 0.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00, 0.e+00, 1.e+00, 1.e+00, 0.e+00, 0.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 1.e+00, 1.e+00, 0.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 1.e+00, 1.e+00,
        0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 1.e+00,
        1.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
        1.e+00, 1.e+00],
       [1.e-10, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00, 0.e+00,
        0.e+00, 1.e+00]])

In [6]:
A_tilde_eval, A_tilde_evec = np.linalg.eig(A_tilde)
print(A_tilde_eval)
print(A_tilde_evec)

[0.9      +0.j         0.9190983+0.05877853j 0.9190983-0.05877853j
 0.9690983+0.09510565j 0.9690983-0.09510565j 1.0309017+0.09510565j
 1.0309017-0.09510565j 1.0809017+0.05877852j 1.0809017-0.05877852j
 1.1      +0.j        ]
[[ 9.94987437e-01+0.00000000e+00j  9.94987437e-01+0.00000000e+00j
   9.94987437e-01-0.00000000e+00j  9.94987437e-01+0.00000000e+00j
   9.94987437e-01-0.00000000e+00j  9.94987437e-01+0.00000000e+00j
   9.94987437e-01-0.00000000e+00j  9.94987437e-01+0.00000000e+00j
   9.94987437e-01-0.00000000e+00j  9.94987437e-01+0.00000000e+00j]
 [-9.94987478e-02+0.00000000e+00j -8.04961757e-02+5.84838981e-02j
  -8.04961757e-02-5.84838981e-02j -3.07467993e-02+9.46289308e-02j
  -3.07467993e-02-9.46289308e-02j  3.07468058e-02+9.46289260e-02j
   3.07468058e-02-9.46289260e-02j  8.04961732e-02+5.84838907e-02j
   8.04961732e-02-5.84838907e-02j  9.94987401e-02+0.00000000e+00j]
 [ 9.94987520e-03+0.00000000e+00j  3.07468000e-03-9.46289364e-03j
   3.07468000e-03+9.46289364e-03j -8.04961810e-

In [7]:
diff = np.abs(A_tilde_eval.real - A_eval)

In [8]:
diff.mean()

0.06472135948651472

In [42]:
p = lambda z: z ** 6 - 1
u = lambda z: (6 * z ** 5) / (z**6 - 1)
u_prime = lambda z: -(6 * z ** 4 * (z**6 + 5))/((z**6 - 1)**2)

def L(x):
    s = np.sign((x ** 3).real)
    z = s * x ** 3
    return x ** -2 * s * (1 + 5*z)/(z + 5)

In [46]:
def laguerre(x, u, u_prime, n=6):
    L_p = n / (-u(x) + np.sqrt((n - 1) * (-n * u_prime(x) - u(x) ** 2)))
    L_m = n / (-u(x) - np.sqrt((n - 1) * (-n * u_prime(x) - u(x) ** 2)))
    if np.abs(L_p) > np.abs(L_m):
        return x - L_p
    else:
        return x - L_m
    

In [52]:
laguerre(5, u, u_prime)

10.208000000000004

In [51]:
L(5)

0.1926153846153846